**Training Pipeline**

**Planning Attack**
1. We will build a simple neural network.  
2. Train it on a real world dataset.  
3. we will mimic the PyTorch workflow.  
4. Will have a lot of manual elements.  
5. End result is not important.

**Code Flow**
1. Load the dataset.  
2. Basic preprocessing.
3. Training process.  
 a. Create the model.  
 b. Forward pass.  
 c. Loss calculation.  
 d. Backdrop.  
 e. Parameters Update.
4. Model evalution.

In [2]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [5]:
df.shape #33 cols and 569 rows

(569, 33)

In [6]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [7]:
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [8]:
df.shape

(569, 31)

**Train test split**.

	•	df.iloc[:,1:] → X (features)  
	•	Takes all rows (:)
	•	Takes all columns from index 1 onward
	•	This is your input data (features)
	•	df.iloc[:,0] → y (target)
	•	Takes all rows
	•	Takes only the first column (index 0)
	•	This is your output/label
	•	test_size=0.2
	•	20% of data → testing set
	•	80% → training set

In [9]:
X_train, X_test, y_train, y_test=train_test_split(df.iloc[:,1:], df.iloc[:,0],test_size=0.2)

**Scaling**.

scalar = StandardScaler().  

	•	Creates a scaler object
	•	It will standardize features (mean = 0, standard deviation = 1).

X_train = scalar.fit_transform(X_train).  

	•	fit → learns mean and std from training data
	•	transform → scales the data using those values
	•	So training data becomes standardized

X_test = scalar.transform(X_test).

	•	Only transform, NOT fit
	•	Uses same mean & std learned from training data
	•	Prevents data leakage

In [11]:
scalar=StandardScaler()
X_train=scalar.fit_transform(X_train)
X_test=scalar.transform(X_test)

In [12]:
X_train

array([[ 1.19657597, -0.15794734,  1.10631885, ...,  0.64479681,
         0.51418395, -0.81836316],
       [-0.26955212,  1.37444128, -0.33336336, ..., -0.83801348,
        -0.77227776, -0.90067586],
       [-0.34717066, -0.71162898, -0.37175488, ..., -0.473919  ,
         0.66781652, -0.32668194],
       ...,
       [-0.53115537, -0.77365971, -0.55328003, ..., -1.01983154,
        -0.7081235 , -1.16517402],
       [ 1.24832167, -0.40147537,  1.21898963, ...,  0.78536203,
        -0.66085194,  0.55735651],
       [-0.8675024 , -0.60824445, -0.90214215, ..., -1.1376313 ,
        -0.87526223, -0.73879421]])

In [13]:
y_train

186    M
457    B
403    B
386    B
161    M
      ..
223    M
309    B
189    B
498    M
428    B
Name: diagnosis, Length: 455, dtype: object

since y_train output is in alphabet so we have to label encode it---> M,B is in Alphabet

**Label Encoding**

In [15]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [17]:
y_train #label encoded

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0])

**Converting Numpy arrays to PyTorch tensors**

In [18]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [19]:
X_train_tensor.shape

torch.Size([455, 30])

In [20]:
y_train_tensor.shape

torch.Size([455])

**Define the model**

In [26]:
class MySimpleNN():
  def __init__(self,X):

    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros (1,dtype=torch.float64, requires_grad=True)

  #forward pass--> z=sigmoid(w*x+b)
  def forward(self,X):
    z=torch.sigmoid(torch.matmul(X, self.weights) + self.bias)
    y_pred=torch.sigmoid(z)
    return y_pred

  #calculate loss function
  def loss_function(self,y_pred,y):

    #clamp prediction to avoid log(0)
    epsilon=1e-7
    y_pred=torch.clamp(y_pred,epsilon,1-epsilon)

    #calculate loss--->cross entropy formula applied
    loss=-(y_train_tensor*torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()
    return loss

**Important Parameters**

In [36]:
learning_rate=0.1
epochs=25

**Training Pipeline**

In [37]:
#create a model
model=MySimpleNN(X_train_tensor)

#define loop
for epoch in range(epochs):

  #forward pass
  y_pred=model.forward(X_train_tensor)

  #loss calculate
  loss=model.loss_function(y_pred,y_train_tensor)

  #backward pass
  loss.backward()

  #parameters update---> Wnew=Wold-lr(dl/dw)
  with torch.no_grad():
    model.weights-=learning_rate*model.weights.grad
    model.bias-=learning_rate*model.bias.grad

  #zero gradients-->we dont want grad to accumulate in every epoch
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss in each epoch
  print(f'Epoch: {epoch+1}, Loss:{loss.item()}')

Epoch: 1, Loss:0.7905283100673922
Epoch: 2, Loss:0.790522032255624
Epoch: 3, Loss:0.7905157566975177
Epoch: 4, Loss:0.7905094833894208
Epoch: 5, Loss:0.7905032123276888
Epoch: 6, Loss:0.7904969435086856
Epoch: 7, Loss:0.7904906769287828
Epoch: 8, Loss:0.7904844125843601
Epoch: 9, Loss:0.7904781504718054
Epoch: 10, Loss:0.7904718905875143
Epoch: 11, Loss:0.7904656329278906
Epoch: 12, Loss:0.7904593774893459
Epoch: 13, Loss:0.7904531242682995
Epoch: 14, Loss:0.7904468732611794
Epoch: 15, Loss:0.7904406244644201
Epoch: 16, Loss:0.7904343778744649
Epoch: 17, Loss:0.7904281334877653
Epoch: 18, Loss:0.7904218913007796
Epoch: 19, Loss:0.7904156513099743
Epoch: 20, Loss:0.7904094135118238
Epoch: 21, Loss:0.79040317790281
Epoch: 22, Loss:0.7903969444794229
Epoch: 23, Loss:0.7903907132381596
Epoch: 24, Loss:0.7903844841755253
Epoch: 25, Loss:0.790378257288033

**Evaluation**

In [40]:
#model evaluation
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  y_pred=(y_pred>0.5).float()
  accuracy=(y_pred==y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.37719297409057617